### ISSUE TITLE
Error when using custom instantiation

### ISSUE THREAD

**Issue by joesamcoke** [clerkinc/clerk-sdk-node#45]
I'm tryng to get this working with sveltekit using the node adapter. I can't use the standard env variable as they do not work with vite.

When use the following code...

import { Clerk } from '@clerk/clerk-sdk-node';

const clerk = new Clerk({ apiKey: 'my_default_api_key' });

I get the error 'Clerk API key not found during initialization.' which seems strange.

I comment out the lines...

        if (!apiKey) {
            throw Error(SupportMessages_1.SupportMessages.API_KEY_NOT_FOUND);
        }

From Clerk.js and I can then make api calls without a problem.

**Comment by igneel64** [comment]
Hey @joesamcoke , thanks for reporting this issue. Checking from our side 😄

**Comment by igneel64** [comment]
@joesamcoke 
We added a patch fix for this case. Now since you need a custom instantiation you can try using:
`import Clerk from '@clerk/clerk-sdk-node/instance'`

**Comment by joesamcoke** [comment]
Thanks
