### ISSUE TITLE
No `createUser` function?

### ISSUE THREAD

**Issue by DavidChouinard** [clerkinc/clerk-sdk-node#54]
Looks like the library supports `getUser`, `updateUser`, etc. but not `createUser`, is that intentional?

**Comment by gkats** [comment]
Hey @DavidChouinard, this is definitely not intentional. Good catch! 

Probably an omission on our part. We'll add a `createUser` method for the user API soon.

**Comment by DavidChouinard** [comment]
Awesome exciting! Happy holidays 🎄

**Comment by DavidChouinard** [comment]
Opened PR #55

**Comment by gkats** [comment]
Updated (and merged) PR in #57.
